x-app-info: &app-info
  build:
    context: .
    dockerfile: Dockerfile
  env_file: .env
  networks:
    - proxy
  tty: true
  init: true

x-service-info: &service-info
  restart: always
  networks:
    - proxy
  logging:
    options:
      max-size: 50m
      max-file: '10'
  init: true

services:
  app:
    <<: *app-info
    container_name: "${APP_NAME}"
    ports:
      - "${APP_EXPOSE_PORT}:5555"
    volumes:
      - "${PROJECT_PATH}:${APP_ROOT}"
      - "${PROJECT_SECRET_PATH}:${APP_SECRET_PATH}"
    restart: always
    command: 'python main.py'
    tty: false
    logging:
      options:
        max-size: 50m
        max-file: '10'
  postgres:
    <<: *service-info
    image: "{POSTGRES_IMAGE}"
    container_name: "${POSTGRES_CONTAINER_NAME}"
    ports:
      - "${APP_EXPOSE_PORT}:5432"
    volumes:
      - "${DB_PATH}/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "${POSTGRES_ADMIN}"
      POSTGRES_PASSWORD: "${POSTGRES_PASS}"
      POSTGRES_DB: "${DB_NAME}"

networks:
  proxy:
    name: "${DB_NAME}"
