[tool.poetry]
name = "linebot"
version = "0.1.0"
description = ""
authors = ["EricKuo <eric.kuo@neualgo.co>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10.13"
flask = "^3.1.0"
pydantic = "^2.10.6"
gunicorn = "^23.0.0"
line-bot-sdk = "^3.16.0"
flask-cors = "^5.0.1"
flask-compress = "^1.17"
rejson = "^0.5.6"
schema = "^0.7.7"
pygsheets = "^2.0.6"
pydantic-settings = "^2.9.1"
flask-sqlalchemy = "^3.1.1"
psycopg2-binary = "^2.9.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
