########################
# Redis 基本設定
########################

bind 0.0.0.0
protected-mode no
port 6379
timeout 0
tcp-keepalive 300

########################
# 背景執行與日誌
########################

daemonize no
supervised no
loglevel notice
logfile ""

########################
# 關閉 RDB 快照
########################

save
stop-writes-on-bgsave-error no

########################
# AOF 設定（持久化）
########################

appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

########################
# 檔案與路徑
########################

dir /data
