from common.const_base import ConstBase


class ErrorCode(ConstBase):
    # System
    BASE_ERROR = 1
    JSON_DECODE_ERROR = 2
    INVALID_OPERATION = 100
    PERMISSION_DENIDE = 101
    DATA_MISSIN = 102
    DATA_ERROR = 103
    REQUIRED = 104
    IMUTABLE = 105
    SIZE_ERROR = 106

    # Schema
    PAYLOAD_ERROR = 201
    PAYLOAD_MISSING_KEY = 202
    PAYLOAD_UNEXPECTED_TYPE = 203
    USERNAME_FORMAT_ERROR = 204
    PASSWORD_FORMAT_ERROR = 205
    EMAIL_FORMAT_ERROR = 206
    PHONE_FORMAT_ERROR = 207

    # Token
    INVALID_TOKEN = 220
    TOKEN_EXPIRED = 221
    TOKEN_NOT_EXIST = 222
    NEED_AUTH_TOKEN = 223

    # User
    USER_IS_BLOCK = 240
    USER_IS_EXIST = 241
    USER_NOT_EXIST = 243
    USER_NOT_EXIST_OR_WRONG_PASSWORD = 243
    INVALID_PASSWORD = 244

    # File
    IMAGE_TO_BIG = 245
    IMAGE_WRONG_TYPE = 246
    TEXT_TO0_BIG = 247

    # External Service
    SERVICE_ERROR = 300

    # Unknown
    UNKNOWN_ERROR = 500
